<!-- footer.inc -->
                <div class="footer-main">
                    <p>
                        &copy; {yearDevelop} {nombreProyecto}. Todos los Derechos Reservados<br>
                        Resolución Mínima {resolucionMinima}
                    </p>
                </div> <!-- footer-main -->
            </div> <!-- contenedor -->
        </form> <!-- form -->
    </body>
</html>