<!-- header.inc -->
<!DOCTYPE html> 
<html lang='es'>
    <head>
        <meta charset='utf-8'>
        <meta http-equiv='Cache-Control' content='no-cache, mustrevalidate'>
        <meta http-equiv='refresh' content='1800; url=./cerrar.php'>
        <meta name='author' lang='es' content='ARC'>
        <link rel='shortcut icon' href='images/movistar.ico'>
        <link rel='stylesheet' rev='stylesheet' type='text/css' href='css/style.css'>
        <!--<link rel='stylesheet' type='text/css' href='css/themes/default/easyui.css'>
        <link rel='stylesheet' type='text/css' href='css/themes/icon.css'>-->
        <!--<script type='text/javascript' src='js/jquery-min.js'></script>-->
        <script type='text/javascript' src='js/jquery-1.11.1.min.js'></script>
        <script type='text/javascript' src='js/jquery-ui-1.11.1.min.js'></script>
        <script type='text/javascript' src='js/jquery-easyui.min.js'></script>
        <script type='text/javascript' src='js/funciones.js'></script>
        <script type='text/javascript' src='js/default.js'></script>