<!--errorSesion.inc Plantilla para mostrar Error si la Sesión a Terminado o Caducó.-->
    <body>
        <form id='form1'>
            <div class='contenedor'>
                <img alt='Movistar' class='logotipo' src='images/logo.png' style='margin-left:840px;margin-top:40px;'>
            	<div class='content'>
                	<div id='msg-notif-form' style='display:none;max-width:800px;'></div>
                	<br>
                	<p style='color:red;font-weight:bold;font-size:20px;text-align:center;margin-top:60px;'>USUARIO INACTIVO</p>
                	<input type='button' name='btnReg' onclick="location.href='./';" value='Iniciar Sesión' style='margin-left:475px;margin-top:40px;'>
            	</div> <!-- content -->
        	</div> <!-- contenedor -->
        </form>
    </body>
</html>