<!--errorRequest.inc Plantilla para mostrar mensaje de error cuando se solicte una opción no encontrada.-->   
                </div> <!-- header --> 
                <div class='content'>
                    <p style='color:red;font-weight:bold;text-align:center;margin-top:40px;font-size:18px;'>{mensaje}</p>
                </div> <!-- content -->
            </div> <!-- contenedor -->
            <div class='footer'>
                <p>
                    Gestor de Exportaciones y Reversiones. Todos los Derechos Reservados &copy;<br>
                    Resoluci&oacute;n M&iacute;nima 1280 x 800px
                </p>
            </div> <!-- footer -->
        </form>
  	</body>
</html>