    <body>
        <form id='form1' name='form1'>
            <div class='contenedor'>
                <div class='menu'>
                    <ul>
                        <li>
                            <a href='menu.php'>
                                <img src='images/homeIcon.png' border='0' alt='Inicio' title='Inicio'>
                            </a>
                        </li>
                        <li><a href='bandejas.php?mod=cobranza&acc=con' class='{activoCobranza}' 
                            alt='Bandeja de Cobranza' title='Bandeja de Cobranza'>Bandeja Cobranza</a>
                        </li>
                    </ul>
                </div> <!-- menu -->
                <div class='nombre-usuario'>Nombre: {nombreUsuarioSesion}<a href='cerrar.php' class='texto_salir'>
                Cerrar Sesión</a></div>
                <div class='header'>
                    <img alt='Movistar' class='logotipo' src='images/logo.png'>
            