    <body>
        <form id='form1'>
            <div class='contenedor'>
                <div class='menu'>
                    <ul>
                        <li>
                            <a href='menu.php'>
                                <img src='images/homeIcon.png' border='0' alt='Inicio' title='Inicio'>
                            </a>
                        </li>
                        <li><a href='bandejas.php?mod=cobranza&acc=con'>Bandeja Cobranza</a></li>
                    </ul>
                </div> <!-- menu -->
                <div class='nombre-usuario'>Nombre: {nombreUsuarioSesion}<a href='cerrar.php' class='texto_salir'>
                Cerrar Sesión</a></div>
                <div class='header'>
                    <img alt='Movistar' class='logotipo' src='images/logo.png'>
                    <h1>Bienvenido</h1>
                </div> <!-- header -->
                <div class='content'>
                </div> <!-- content -->
            </div> <!-- contenedor -->
        </form> <!-- form -->
        <div class='footer'>
            <p>
                Gestor de Exportaciones y Reversiones. Todos los Derechos Reservados &copy;<br>
                Resolución Mínima 1280 x 800px
            </p>
        </div> <!-- footer -->
    </body>
</html>