    <body>
        <form id='form1' name='form1'>
        <div class="contenedor" style='width:900px;'>
            <div class="header" style='margin-top:5px;'>
                <img alt="Movistar" class="logotipo" src="images/logo.png" style='margin-left:700px;'>
            </div>
            <div class='nombre-usuario'>Hora Actual Cd. de México: {horaActual} Nombre: {nombreUsuarioSesion}</div>
            