<!-- header.inc -->
<!DOCTYPE html> 
<html lang='es'>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta HTTP-EQUIV=Refresh CONTENT="1800; URL=logout.php">
        <link rel="stylesheet" href="../styles/normalize.css">
        <link rel="stylesheet" href="../styles/main.css">
        <link rel="shortcut icon" href="images/movistar.ico">
        <link href="../styles/style.css" rel="stylesheet" rev="stylesheet" type="text/css">
        <link href="../styles/app.css" rel="stylesheet" rev="stylesheet" type="text/css">
        <link rel="stylesheet" href="../styles/thickbox.css" type="text/css" media="screen"> 
        <link rel="stylesheet" type="text/css" href="../styles/jquery-ui.css">     
        <script src="../scripts/modernizr-2.6.2.min.js"></script>
        <script src="../scripts/jquery-1.8.0.min.js" type="text/javascript"></script>
        <script src="js/funciones.js" type="text/javascript"></script>
        <script src="../scripts/default.js" type="text/javascript"></script>
        <script type="text/javascript" src="../scripts/thickbox.js"></script>
        <script type="text/javascript" src="../scripts/jquery-ui.js"></script>
        <script src="../scripts/jquery-ui-1.9.2.custom.min.js"></script>
        <script src="../scripts/validaciones.js"></script>
        <script src="js/vanilla.js" type="text/javascript"></script>
        